name = "xmcl-web-ai"
account_id = "7af57e4bbecec7133ccf33d2b530b4b5"
main = "worker.ts"
compatibility_date = "2025-03-20"
compatibility_flags = ["nodejs_compat_v2"]

[observability]
enabled = true
head_sampling_rate = 1

[observability.logs]
invocation_logs = false

[observability.traces]
enabled = true
head_sampling_rate = 1

[[routes]]
pattern = "ai.xmcl.app"
custom_domain = true
