name: Deploy to Alibaba Cloud Function

on:
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - 'api/**'
  #     - 'middlewares/**'
  #     - 'shared/**'
  #     - 'utils/**'
  #     - 'index.ts'
  #     - 'aliyun/**'
  #     - 's.yaml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Compile Deno application
        run: |
          deno compile --allow-all \
            --output aliyun/xmcl-api \
            index.ts

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Serverless Devs
        run: npm install -g @serverless-devs/s

      - name: Configure Serverless Devs Access
        run: |
          s config add \
            --AccountID ${{ secrets.ALIYUN_ACCOUNT_ID }} \
            --AccessKeyID ${{ secrets.ALIYUN_ACCESS_KEY_ID }} \
            --AccessKeySecret ${{ secrets.ALIYUN_ACCESS_KEY_SECRET }} \
            --access default

      - name: Deploy to Alibaba Cloud Function
        run: s deploy --use-local -y
